/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./code.html"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#565e74",
        "surface-container-low": "#f2f4f6",
        "tertiary-fixed": "#c4e7ff",
        "inverse-primary": "#bec6e0",
        "surface": "#f7f9fb",
        "on-tertiary-fixed-variant": "#004c69",
        "inverse-on-surface": "#eff1f3",
        "outline-variant": "#c6c6cd",
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-container": "#008ebf",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-variant": "#e0e3e5",
        "secondary-container": "#39b8fd",
        "on-primary-container": "#7c839b",
        "outline": "#76777d",
        "on-surface-variant": "#45464d",
        "on-secondary-fixed": "#001e2f",
        "tertiary-container": "#001e2c",
        "on-tertiary-fixed": "#001e2c",
        "secondary-fixed": "#c9e6ff",
        "surface-bright": "#f7f9fb",
        "primary-container": "#131b2e",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1e",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#7bd0ff",
        "tertiary": "#000000",
        "inverse-surface": "#2d3133",
        "on-secondary-container": "#004666",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#bec6e0",
        "primary": "#000000",
        "on-background": "#191c1e",
        "surface-dim": "#d8dadc",
        "surface-container": "#eceef0",
        "secondary-fixed-dim": "#89ceff",
        "on-primary-fixed": "#131b2e",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-fixed-variant": "#004c6e",
        "surface-container-high": "#e6e8ea",
        "primary-fixed": "#dae2fd",
        "on-error-container": "#93000a",
        "background": "#f7f9fb",
        "secondary": "#006591",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "celeste": "#39b8fd",
        "pastel-pink": "#ffd1dc"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px"
      },
      spacing: {
        lg: "24px",
        gutter: "24px",
        "margin-mobile": "16px",
        sm: "8px",
        md: "16px",
        "margin-desktop": "48px",
        xs: "4px",
        unit: "4px",
        xl: "32px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Inter"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};